### ISSUE TITLE
Scipy 2024 - Tacoma WA - July 8-14 - CFP Open

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/talks#11]
## CFP Deadline 02/27/2024 

https://www.scipy2024.scipy.org/

Conference will be in Tacoma WA at: Tacoma Convention Center: [1500 Commerce Street, Tacoma, WA 98402](https://www.google.com/maps/place/Greater+Tacoma+Convention+Center/@47.248525,-122.4389871,15z/data=!4m2!3m1!1s0x0:0xe464395e6d5c8dd5?sa=X&ved=2ahUKEwi85e--6vjdAhUJNOwKHdMAAaoQ_BIwEHoECAkQCw)

Tutorials: July 8-9  |  Conference: July 10-12  |  Sprints: July 13-14

**Comment by cpcloud** [comment]
Let's submit multiple talks:

- Geospatial @ncclementi 
- Testing @cpcloud 
- The Usual Awesomeness @gforsyth 
- Tutorial (> 1 person) (?)

**Comment by ncclementi** [comment]
I'm going to close this one, in favor of all the individual ones, we can keep track of the status on them.
