### ISSUE TITLE
PyData London - June 14-16  - CFP Open

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/talks#12]
Event: https://pydata.org/london2024/

CFP open, Deadline March 4, 2024 : https://pydata.org/london2024/cfp#submit

**Comment by ncclementi** [comment]
I put the wrong link originally, CFP closes March 4th https://pydata.org/london2024/cfp#submit

**Comment by cpcloud** [comment]
Ah, nice thanks!

**Comment by cpcloud** [comment]
@deepyaman is considering submitting some Ibis + Kedro content here.

**Comment by cpcloud** [comment]
cc @gforsyth for possible tutorial submission
