### ISSUE TITLE
EuroPython - July 8-14th - overlaps with Scipy

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/talks#13]
It is the exact same dates than with SciPy 2024. :/

Event: https://ep2024.europython.eu/

**Comment by cpcloud** [comment]
@kszucs Any interest in presenting an Ibis talk at EuroPython?

**Comment by kszucs** [comment]
Perhaps.

**Comment by cpcloud** [comment]
https://ep2024.europython.eu/cfp/
