### ISSUE TITLE
P99 CONF 

### ISSUE THREAD

**Issue by lostmygithubaccount** [ibis-project/talks#16]
https://www.p99conf.io/

this is a "low latency" streaming conference that could be good to present Ibis streaming backends at

**Comment by cpcloud** [comment]
@lostmygithubaccount Ping on updating the details here :)

**Comment by cpcloud** [comment]
Ping!

**Comment by cpcloud** [comment]
Ping! What's the deadline for this conference?

**Comment by cpcloud** [comment]
@ianmcook Any idea if p99conf is happening this year?
