### ISSUE TITLE
Snowflake Data Cloud Summit 2024

### ISSUE THREAD

**Issue by cpcloud** [ibis-project/talks#17]
# Description

https://www.snowflake.com/summit/

Snowflake Data Cloud Summit 2024 is the annual Snowflake conference where folks come together to discuss and present on all things Snowflake.

# Abstract

Snowflake has become a pivotal platform for storing, processing, and analyzing data. Its recent addition of Python support through Snowpark has redefined traditional workflows, marking a significant milestone in data science and engineering.

In this session, we delve into Snowflake and Python interoperability using the capabilities of [the Ibis project](https://github.com/ibis-project/ibis) to optimize feature engineering, data preprocessing and general interactive data analysis.

Ibis draws inspiration from your favorite DataFrame APIs, focusing more on the pandas and dplyr lineage over PySpark. This allows users familiar with those libraries to hit the ground running with Snowflake and be productive out of the box.

In this talk, we'll show the many ways to be productive with Snowflake + Ibis, including typical SQL workflows, preprocessing, user-defined functions and more! We might even throw in an LLM or two!

**Comment by cpcloud** [comment]
cc @ianmcook and @indexseek for feedback

**Comment by ncclementi** [comment]
Small comment, not sure if it's on purpose, but you have the "We might even throw in an LLM or two!" twice, in the second and fourth paragraph.

**Comment by cpcloud** [comment]
@ncclementi Thanks, fixed!

**Comment by sfc-gh-twhite** [comment]
This looks good to me! 

My grammar tool says there should be a comma in "feature engineering, data preprocessing and general interactive data analysis." and "including typical SQL workflows, preprocessing, user-defined functions and more!" 

Were you able to come up with a title for the session?

**Comment by cpcloud** [comment]
This was submitted yesterday (2024-01-30)! Waiting to hear back 🤞🏻

**Comment by cpcloud** [comment]
This was declined :(
