### ISSUE TITLE
Data Council 2024

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/talks#18]
### Title

Unified Stream/Batch Execution with Ibis

### Abstract

Libraries like Ibis have been gaining traction recently, by unifying the way we work with data across multiple data platforms—from dataframe APIs to databases, from dev to prod. What if we could extend the abstraction to unify the way we work across batch and streaming contexts? In this presentation, we showcase our work adding streaming concepts and an Apache Flink backend to the open-source Ibis project.

### Key points of draft presentation plan

* What is Ibis? Motivation, examples, etc.
* How does Ibis work? Building expression trees, compiling to different backends (string generation vs. expression generation vs. direct execution)
* Why streaming? Parallel motivation, new concepts, practical/real-world application of unifying batch and streaming
* Demo: define a (Flink) streaming workload, execute it, run the exact same code against a batch engine (e.g. DuckDB)
* Limitations (i.e. streaming and batch are still different)
* Roadmap for streaming functionality in Ibis

**Comment by ncclementi** [comment]
Closing as this talk was delivered!
