### ISSUE TITLE
Berlin Buzzwords 2024 - June 9-11, 2024

### ISSUE THREAD

**Issue by chloeh13q** [ibis-project/talks#24]
Thinking about submitting a talk on ibis-streaming to Berlin Buzzwords.

CFP: https://2024.berlinbuzzwords.de/call-for-papers/

> Berlin Buzzwords is looking for talks on
> …any aspect of search: From search engines to relevance engineering, and more.
…Data Science and Making sense of data: AI, ML, Data Wrangling, Data Engineering, MLOps, A/B-testing, etc.
…everything related to stream processing
…Operations / Infrastructure, including building and maintaining infrastructure, but also delivery and testing.
…Scaling up (taking better advantage of a single machine, with threads, accelerators, specialized libraries, …), scaling out (distribution) or even scaling down; including moving from centralized services to “on device”.
…Storing data and everything that entails.
…experiments, hacks and novel approaches, but also lessons learned, generally-useful algorithms, and experience reports.
…societal, environmental and ethical impact of tech.
…Management, Leadership, Team Culture and internal processes, as well as Open Source & Governance.
The list is not complete and we are always happy about new and unique submissions. If you are looking for inspiration, please check out our [YouTube channel](https://www.youtube.com/@PlainSchwarzUG/playlists?view=50&sort=dd&shelf_id=3) to see videos of previous years’ talks.

> Please note that we do not accept product presentations or company marketing presentations. If your company is interested in a media partnership or sponsorship, please contact Mareike at [partner@berlinbuzzwords.de](mailto:partner@berlinbuzzwords.de)

**Comment by ncclementi** [comment]
Note: CFP closes February 25th, 2024, 23:59 CET

**Comment by ncclementi** [comment]
Closing, since this was delivered!
