### ISSUE TITLE
Community over Code 2024

### ISSUE THREAD

**Issue by deepyaman** [ibis-project/talks#27]
https://communityovercode.org/
Denver, Colorado,
October 7-10, 2024

There is also a stream processing track:

> Hi all,
> 
> [Community Over Code](https://communityovercode.org/), the ASF conference, will be held in Denver, Colorado,
October 7-10, 2024. The [call for presentations](https://news.apache.org/foundation/entry/apache-software-foundation-opens-cfp-for-community-over-code-north-america-2024) is open now through April 15, 2024.  (This is two months earlier than last year!)
> 
> I am one of the co-chairs for the stream processing track, and we would love to see you there and hope that you will consider submitting a talk.
> 
> About the Streaming track:
> 
> There are many top-level ASF projects which focus on and push the envelope for stream and event processing.  ActiveMQ, Beam, Bookkeeper, Camel, Flink, Kafka, Pulsar, RocketMQ, and Spark are all house-hold names in the stream processing and analytics world at this point.  These projects show that stream processing has unique characteristics requiring deep expertise.  On the other hand, users need easy to apply solutions.  The streaming track will host talks focused on the use cases and advances of these projects as well as other developments in the streaming world.  
> 
> Thanks and see you in October!
> 
> Jim

**Comment by chloeh13q** [comment]
I'm thinking about submitting to this!

**Comment by ncclementi** [comment]
Looks like we missed the deadline for this one, it was 04/15. I would close this issue unless @chloeh13q or @deepyaman you submitted something.

**Comment by deepyaman** [comment]
Nothing from my end!

**Comment by chloeh13q** [comment]
Same here. Did not end up submitting. Closing this issue.
