### ISSUE TITLE
Flink Forward Berlin 2024 - CFP due 5/31

### ISSUE THREAD

**Issue by chloeh13q** [ibis-project/talks#34]
[CFP link](https://sessionize.com/flink-forward-2024-berlin?utm_campaign=Flink%20Forward%20Berlin%202024&utm_medium=email&_hsenc=p2ANqtz--UOiHBmCbxFmrm4Y9LA23wWaI__UVMcUbMbwQRV2_SUwYmBHrhkAKwQORp1zvxd5vEaYU6maUJZx8Im0OcgGAGhUOxDw&_hsmi=302715730&utm_content=302714744&utm_source=hs_email)

Topics for Consideration

- Developing Real-Time Applications - All things related to building applications with streaming technologies, including development practices, testing, scaling, and more.
- Streaming Technologies - Anything streaming, from introductory talks to technical deep dives. 
- Architecture - What tools and processes do you or your business use alongside a Flink deployment? Share integrations and connectors you are using to create unique architectures and solve surprising use cases.
- Solution Stories (use cases / case studies) - How do you use data streaming in your business? Why did you adopt it? What problems does it solve (or create)? What lessons did you learn that might help others on a similar journey?
- Operations and Observability - SREs, share your successes, learning opportunities, and experience with operating a streaming pipeline or streaming technologies, both in the cloud and on-premises. 
- Pipelines Done Right - Streaming ETL, Batch Pipelines, or something in between!
- Real-time Analytics - What use cases does a real-time dashboard serve? How are you building dashboards? Do you even need to capture data in real-time for analytics?
- Nerding Out! - Do you have a random idea or side hobby that is SUPER interesting but might have little to do with traditional event streaming? Perhaps you have a novel way of using Flink outside the normal applications? Or just an entertaining talk about the nuances of git or AI…if it’s fun and shareable, submit! 
- Academia and Beyond - Do you have a history lesson or theory to share that includes data streaming? Or do you use real-time data applications in your academic studies? Submit your talk for consideration!

Going to try to submit something on streaming here!

**Comment by chloeh13q** [comment]
Going to assign to myself but feel free to add yourself if you want to submit a proposal as well.

**Comment by ncclementi** [comment]
Did we submit something for Flink forward?

**Comment by chloeh13q** [comment]
I think Deepyaman did, and I'm going to. Deadline has been extended.

**Comment by ncclementi** [comment]
Oh, I see this https://github.com/ibis-project/talks/issues/35.

**Comment by ncclementi** [comment]
@chloeh13q do you mind updating the title to reflect the new CFP 31st of May

**Comment by chloeh13q** [comment]
@ncclementi Done!

**Comment by ncclementi** [comment]
@chloeh13q did you hear back from them or can we close this?

**Comment by chloeh13q** [comment]
@ncclementi Both my and Deepyaman's proposals were rejected. Closing
