### ISSUE TITLE
PGConf NYC 2024 - CFP closes June 5th

### ISSUE THREAD

**Issue by ncclementi** [ibis-project/talks#36]
While at PyCon US, we discover there are couple of postgress conferences coming up, the most relevant one due to location is the NYC one. 

https://2024.pgconf.nyc/

The CFP closes June 5th. We might want to consider repurposing one of our talks, making it postgres oriented and apply. 

Thinking of @cpcloud and @gforsyth since they are close-ish to NYC.

**Comment by gforsyth** [comment]
I'm not going to be around to get a submission in for this, but if someone puts in a submission, I can be the one to present.

**Comment by cpcloud** [comment]
I will actually be away for those dates, so I cannot make the conference itself. I think the person who submits should probably be attending in some capacity

**Comment by cpcloud** [comment]
Chatted in triage about this and we think it's probably not a conference that would have a huge impact on Ibis so we're not going to submit this year.
